### ISSUE TITLE
Deleting a Poll

### ISSUE THREAD

**Issue by Sahil624** [Sahil624/voting-app#2]
Still Deleting a poll is to be done.

**Comment by sudo-win** [comment]
elaborate the issue

**Comment by Sahil624** [comment]
@revu-vinay 

The deleting Poll feature is not working. When we click on Delete poll button It takes me back to poll page without deleting. 
You can run it locally then you can understand the problems with the errors.

**Comment by Sahil624** [comment]
@revu-vinay I ran your code today And I Got Some errors. I am attaching a picture of Error.

![err](https://user-images.githubusercontent.com/20486172/28500143-8bf60b38-6fe1-11e7-87d9-85dfb8e42c33.jpg)


You might want to see It.
Have a Nice day.

**Comment by cmdrwebdev** [comment]
Hi @Sahil624 is this still open?

**Comment by Sahil624** [comment]
@cmdrwebdev Sorry, This Bug Is just fixed in the last Merge. But another Issue is open. you Can Try It.

**Comment by Sahil624** [comment]
Issue Was fixed in the last Merge.
