### ISSUE TITLE
Null vote when nothing is selected

### ISSUE THREAD

**Issue by Sahil624** [Sahil624/voting-app#3]
When a poll is submitted without selecting any option then null gets submitted

**Comment by chrisjamesr** [comment]
Hey Sahil
 This looks like something I can take care of as a first time contributor if you would like the help.

**Comment by Sahil624** [comment]
@chrisjamesr Sure Go ahead.Tell if You need anything.

**Comment by wonntann** [comment]
Hi, this is a first-timer contribution. Is this project still open? I am not able to replicate the issue. There are no action items available. Not sure if the issue is just on my end, user error.

**Comment by Sahil624** [comment]
@wonntann Hi!!
Sorry this issue is solved now ,I think I forgot to close this isuue.
Sorry!!
